"""Minimal: an asset that asks Compass and stores the answer as markdown metadata.

Run::

    export DAGSTER_CLOUD_URL='https://my-org.dagster.cloud/prod/graphql'
    export DAGSTER_CLOUD_API_TOKEN='user:...'
    dagster dev -m examples.basic_resource
"""

from dagster import Definitions, EnvVar, MaterializeResult, MetadataValue, asset

from dagster_compass_kit import CompassResource


@asset(description="Weekly pipeline-health digest generated by Compass")
def weekly_digest(compass: CompassResource) -> MaterializeResult:
    response = compass.ask(
        "Summarize this week's pipeline health. Call out top failures and "
        "anything trending slower. Format as markdown."
    )
    body = response.text or "(no digest)"
    if response.error:
        body = f"(compass error: {response.error})\n\n{body}"
    return MaterializeResult(
        metadata={
            "digest": MetadataValue.md(body),
            "tool_calls": MetadataValue.int(len(response.tool_calls)),
        }
    )


defs = Definitions(
    assets=[weekly_digest],
    resources={
        "compass": CompassResource(
            dagster_cloud_url=EnvVar("DAGSTER_CLOUD_URL"),
            api_token=EnvVar("DAGSTER_CLOUD_API_TOKEN"),
        ),
    },
)
