"""Compass-generated runbook stored as an asset.

Runs on a schedule, asks Compass to synthesize a runbook for a given job
based on recent history, stores it as markdown metadata on a Dagster asset.
The runbook stays current because it re-materializes periodically — always
grounded in the latest operational state.
"""

from dagster import AssetExecutionContext, Definitions, EnvVar, MaterializeResult, MetadataValue, asset

from dagster_compass_kit import CompassResource


@asset(description="Up-to-date runbook for the orders_pipeline job, generated by Compass")
def orders_pipeline_runbook(
    context: AssetExecutionContext,
    compass: CompassResource,
) -> MaterializeResult:
    markdown = compass.generate_job_runbook(job_name="orders_pipeline")
    return MaterializeResult(metadata={"runbook": MetadataValue.md(markdown)})


defs = Definitions(
    assets=[orders_pipeline_runbook],
    resources={
        "compass": CompassResource(
            dagster_cloud_url=EnvVar("DAGSTER_CLOUD_URL"),
            api_token=EnvVar("DAGSTER_CLOUD_API_TOKEN"),
        ),
    },
)
